### ISSUE TITLE
Fix for IsConnectedOrUnkown looks to be deleted

### ISSUE THREAD

**Issue by ertanden** [ligi/SnackEngage#12]
I had a pull request numbered #11 for Issue #10. It was merged and the issue was fixed.

However, the latest master branch does not contain this fix. The merge is not even in the commit log. Looks like there was a "force push" done which deleted the fix totally.

**Comment by ligi** [comment]
Thanks for the info!  Was merging via the webinterface but had rebased changes locally - sorry for this. Will try to restore the change - I think I remember what was the problem.

**Comment by ligi** [comment]
Restored your commit - thanks!
