### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by johnjohndoe** [ligi/SnackEngage#14]
I noticed that you [CHANGELOG.md](https://github.com/ligi/SnackEngage/blob/0.14/CHANGELOG.md) is not updated for quite a while. It contains information until v.0.3 Currently, v.0.14 is published.

**Comment by johnjohndoe** [comment]
Are you not going to provide changelog information? 😢

**Comment by ligi** [comment]
There is the git-history - but as seen with this issue I am really bad with caring for this - so I better removed it - because a outdated changelog is also not helping anyone ..

**Comment by johnjohndoe** [comment]
True. However, a changelog might attract more people to use the library. I however respect your decision since I know it is a lot of work to maintain one.
