### ISSUE TITLE
Version increase for release 0.19

### ISSUE THREAD

**Issue by johnjohndoe** [ligi/SnackEngage#36]
There is a tag for [0.19](https://github.com/ligi/SnackEngage/releases/tag/0.19) and I am able to download an artifact for that version because I directly depend on the Git tag which is referenced via JitPack:

``` groovy
implementation com.github.ligi.snackengage:snackengage-playrate:0.19
```

However, the `version_name` and `version_code` properties have **not** been changed from `0.18` to `0.19` resp. from `18` to `19`. See https://github.com/ligi/SnackEngage/blob/0.19/build.gradle#L5-L6.

---

If this is an error please apply a "fix" **before** merging pull requests #34 and #35 so it will still be possible to depend on a library artifact which is based on SDK 27 and support library 27.1.1.

**Comment by ligi** [comment]
fixed by having version 0.20
