### ISSUE TITLE
Multiple Snacks with same condition

### ISSUE THREAD

**Issue by ertanden** [ligi/SnackEngage#8]
I have multiple snacks with same conditions.

The condition I apply for both snacks are `AfterNumberOfOpportunities(3)`.

In this case always the first snack defined in the builder is shown and I never see the second snack shown.

What I expect is in the 4th opportunity show first snack, then in the 5th opportunity show second snack, since condition 5 > 3 is true.

I believe this problem occurs because in `SnackStats` class the method `getLastSnackShow()` returns generic value, instead of "per Snack" values which is defined by the KEY_LAST_SNACK_SHOW + the Snack unique id.

I hope I was clear.

**Comment by ligi** [comment]
can you show me your code?

**Comment by ligi** [comment]
never mind - will release 0.6 which supports this use-case soon to jitpack
